#!/bin/bash

mkdir travis_builds

cd travis_builds

# samtools
git clone https://github.com/samtools/samtools.git
cd samtools
git checkout tags/0.1.18
perl -p -i -e 's/^(CFLAGS=\s+)[^\n]*/$1-g -Wall -O2 -fPIC #-m64 #-arch ppc/' Makefile
make 2>&1 | tail -n 1
cd ..

# push Bio-Root to front
git clone https://github.com/bioperl/Bio-Root.git
export PERL5LIB=$( pwd )/Bio-Root/lib:$( pwd ):$PERL5LIB

cpanm Bio::ASN1::EntrezGene 2>&1 | tail -n 1
export SAMTOOLS=$( pwd )/samtools

cpanm Bio::DB::Sam 2>&1 | tail -n 1

exit 0
