#!/bin/bash

git clone https://github.com/samtools/samtools.git
cd samtools
git checkout tags/0.1.18
perl -p -i -e 's/^(CFLAGS=\s+)[^\n]*/$1-g -Wall -O2 -fPIC #-m64 #-arch ppc/' Makefile

make 

exit 0
