>P1;CCHU
cytochrome c [validated] - human
MGDVEKGKKIFIMKCSQCHTVEKGGKHKTGPNLHGLFGRKTGQAPGYSYTAANKNKGIIWGEDTLMEYLENPKKYIPGTKMIFVGIKKKEERADLIAYLKKATNE*
>P1;CCCZ
cytochrome c - chimpanzee (tentative sequence)
GDVEKGKKIFIMKCSQCHTVEKGGKHKTGPNLHGLFGRKTGQAPGYSYTAANKNKGIIWGEDTLMEYLENPKKYIPGTKMIFVGIKKKEERADLIAYLKKATNE*
>P1;CCST
cytochrome c - snapping turtle (tentative sequence)
GDVEK.GKKIF.VQKCAQCHTVEKGGKH.KTGPNLNGL.IGRKTGQAEGF.SYTEANKN.KGITWG.EETLM.EY.LENPKKY.IPGTKM.IF.AGIKKKAERADL.IAY.LKDATSK*
>P1;CCFG
cytochrome c - bullfrog (tentative sequence)
GDVEKGKKIF(V,Q.K.C.A.Q.C.H.T.C,E.K.G.G.K.H)KVGPNLYGLIGRKTGQAAGFSYTDANKNKGITW(G.E,D,T.L.M.E.Y)LENPKKYIPGTKMIFAGI(K.K.K.G.E.R.Q)DLIAY(L.K.S,A,C,S,K)*
>P1;CCND
cytochrome c - love-in-a-mist (tentative sequence)
AS.F.BZAPAGBSAS(G.E.K)I.F.KTKCAZCHTVBZGAGH.KZGP(N.L)H.G.L.F.GRQSGT.VAG.Y.SY.SAANKN.KAVN.W.EEKT.L.Y.DYLLNPKK.Y.IP(G.T.K.M)VFPGL.KKPZZRABL.LA.Y.LKESTA*
>F1;C44264
ALL-1/AF-4 clone 25 mutant fusion protein - human (fragment)
/EKPPPVNKQENAGTLNIFSTLSNGNSSKQKIPADGVHRIRVDFKTYSNEVHCVEEILKEMTHSWPPPLTAIHTPSTAEPSKFPFPTKDSQHVSSVTQNQKQYDTSSKTHSNSQQGTSSMLEDDLQLSDSEDSDS/*
